

XLEN?=32
ONNX_MODEL              ?= ${ROOT_DIR}/toolchain/onnx-mlir/test-isolde/gemm/models/onnx/gemm_model.onnx
APP=resnet18

include ${ROOT_DIR}/toolchain/onnx-mlir/test-isolde/common/common.mk

all: graph.test.aismem









